### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by MagnusBee** [tnt-debug/ragempscripts#1]
¿Trabajas en algún servidor?

**Comment by tnt-debug** [comment]
> ¿Trabajas en algún servidor?

Hola, no, no trabajo en ningún servidor.

**Comment by MagnusBee** [comment]
Buen día!, Yo estoy haciendo un servidor roleplay, casi desde cero, si tienes conocimientos de javascript y te interesa ayudarme puedes agregarme a discord y lo hablamos. Dacoe#0969. un saludo!!
